version: "3.1"

services:
  certupdater:
    build: .
    env_file:
      - env.env
    image: certupdater:0.1.0
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - </folder/to/store/the/certs/here>:/certs/:rw
